/**
 * Assembles the deployable site into `public/` — the directory Vercel (and
 * most static hosts) serve by default.
 *
 * `tsc` has already compiled src/ → dist/. This step gathers the three pieces
 * the browser actually needs — index.html, styles/, dist/ — into one
 * self-contained folder, preserving the relative layout index.html expects
 * (`styles/main.css`, `dist/main.js`). Run after tsc; see the `build` script.
 *
 * Zero dependencies: `node tools/build.ts` (Node ≥ 22.18 strips the types).
 */
import { cp, rm, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT = join(ROOT, 'public');

// Each entry is copied from the repo root into public/ at the same name, so
// index.html's relative `styles/…` and `dist/…` references keep resolving, and
// every crawler/share file resolves at the site root (`/robots.txt`, `/og-image.png`).
const ASSETS = [
  // app shell
  'index.html', 'styles', 'dist',
  // SEO / crawler / install files
  'robots.txt', 'sitemap.xml', 'site.webmanifest', 'browserconfig.xml',
  'humans.txt', '404.html', '.well-known',
  // favicons · app icons · social card — generated by `yarn assets`, committed
  // because the deploy host can't rasterise SVG (see tools/make-assets.ts).
  'favicon.ico', 'favicon.svg', 'favicon-16.png', 'favicon-32.png',
  'apple-touch-icon.png', 'icon-192.png', 'icon-512.png',
  'icon-maskable-512.png', 'og-image.png',
  // attribution mark shown in the menu + README
  'SINDBUG.gif',
  // custom-domain marker — used by GitHub Pages, harmless elsewhere
  'CNAME',
];

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

for (const asset of ASSETS) {
  await cp(join(ROOT, asset), join(OUT, asset), { recursive: true });
}

console.log(`built → public/ (${ASSETS.join(', ')})`);
